language: node_js

node_js:
  - '4'

sudo: false

install:
  - travis_retry npm install

script:
  - npm test
  - ./scripts/eslint.sh

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
